### ISSUE TITLE
irrelevant tag 

### ISSUE THREAD

**Issue by trapvpack** [objectionary/eoc#388]
@yegor256 While fixing #368 I encountered a problem: the project didn't build on the first run. The possible cause seems to be an irrelevant tag that was missed when bumping the EO version. I suppose this issue occurred in commit [cede36f9cc805ca4bfe1c012bb69dbfb575e4162](https://github.com/trapvpack/eoc/commit/cede36f9cc805ca4bfe1c012bb69dbfb575e4162). My question is, where can I find this tag to attempt a fix for the issue?

**Comment by yegor256** [comment]
@trapvpack I'm not sure I follow. What exactly is wrong and how do you suggest fixing it?

**Comment by trapvpack** [comment]
@yegor256 I assume that the home-tag.txt file should have been updated

**Comment by yegor256** [comment]
@trapvpack it is updated: https://github.com/objectionary/home/blob/gh-pages/tags.txt (what's missing here?)

**Comment by yegor256** [comment]
@trapvpack I believe, it's fixed now in the `master` branch

**Comment by trapvpack** [comment]
@yegor256 the tag was not updated in this PR - #399. But that's not the whole problem, after updating the tag locally, it still doesn't work. I tried to juggle the versions a little, but it didn’t work out for me, please take a look

**Comment by yegor256** [comment]
@trapvpack now, the `master` branch builds clean, at the first attempt or any others. Please, check
